### ISSUE TITLE
Two unique sections have the same name

### ISSUE THREAD

**Issue by JohnDoorenbos** [NorseCourse/NorseCourse-Backend#6]
When I query the sections api for HIST-239 (special topics course with courseId 379), I get two sections, both with unique sectionIds but the same name (both are HIST-239-A)

**Comment by GrantFBarnes** [comment]
That is because there are in fact two separate sections.  One is ST:Comp Eurp Welf States, the other is Africa & the Two World Wars.  One is taught MWF, the other TR.  They are the same course, but they have two different sections.  They should be titled A and B, but the CSV file we were given has them both labeled as A.  It is good that they are in the database as separate courses, because in fact they are.  They are just titled the same. It is even this way on my.luther course search, they are named the same. There is nothing to change or fix for this.
